name: Deploy to Tomcat Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar la clave SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      # Paso 3: Test conexión SSH
      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no ubuntu@rides.iaz7.com "echo 'SSH connection successful'"
        
      # Paso 4: Confirmar si ROOT.war existe
      - name: Check if ROOT.war exists
        run: ssh ubuntu@rides.iaz7.com "[ -f /opt/tomcat/webapps/ROOT.war ] && echo 'Existing ROOT.war found' || echo 'No existing file'"

      # Paso 5: Instalar Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # Paso 6: Construir el archivo .war
      - name: Build .war
        run: |
          mvn clean package
          mv target/*.war app.war

      # Paso 7: Subir el archivo .war al servidor
      - name: Deploy to server
        run: |
          scp app.war ubuntu@rides.iaz7.com:/tmp/ROOT.war
          ssh ubuntu@rides.iaz7.com "sudo mv /tmp/ROOT.war /opt/tomcat/webapps/ROOT.war"

      # Paso 8: Reiniciar Tomcat
      - name: Restart Tomcat
        run: |
          ssh ubuntu@rides.iaz7.com "sudo systemctl restart tomcat"

      # Paso 9: Verificar logs de Tomcat
      - name: Check Tomcat logs
        run: ssh ubuntu@rides.iaz7.com "sudo tail -n 50 /opt/tomcat/logs/catalina.out"
