name: Deploy to Tomcat Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar la clave SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Paso 3: Test conexión SSH
      - name: Test SSH Connection
        run: ssh ubuntu@rides.iaz7.com "echo 'Connection successful'"

      # Paso 4: Confirmar si ROOT.war existe
      - name: Check if ROOT.war exists
        run: ssh ubuntu@rides.iaz7.com "[ -f /opt/tomcat/webapps/ROOT.war ] && echo 'Existing ROOT.war found' || echo 'No existing file'"

      # Paso 5: Construir el archivo .war (opcional)
      - name: Build .war
        run: |
          ./mvnw clean package
          mv target/*.war app.war

      # Paso 6: Subir el archivo .war al servidor
      - name: Deploy to server
        run: |
          scp app.war ubuntu@rides.iaz7.com:/opt/tomcat/webapps/ROOT.war

      # Paso 7: Reiniciar Tomcat
      - name: Restart Tomcat
        run: |
          ssh ubuntu@rides.iaz7.com "sudo systemctl restart tomcat"

      # Paso 8: Verificar logs de Tomcat
      - name: Check Tomcat logs
        run: ssh ubuntu@rides.iaz7.com "tail -n 50 /opt/tomcat/logs/catalina.out"
