name: Deploy to Tomcat Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # Paso 3: Construir el archivo .war
      - name: Build .war
        run: |
          mvn clean package
          mv target/*.war app.war

      # Paso 4: Configurar SSH
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Paso 5: Probar conexión SSH
      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa ubuntu@rides.iaz7.com "echo 'SSH connection successful'"

      # Paso 6: Subir el archivo .war
      - name: Deploy WAR
        run: |
          scp -i ~/.ssh/id_rsa app.war ubuntu@rides.iaz7.com:/opt/tomcat/webapps/ROOT.war

      # Paso 7: Reiniciar Tomcat
      - name: Restart Tomcat
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@rides.iaz7.com "sudo systemctl restart tomcat"
